FROM python:3.11.9-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 502

RUN mkdir -p logs \
            files

VOLUME  ["/app/logs", \
        "/app/files"]

CMD ["python", "modbus_writer.py"]
