FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir redis

COPY . /app

RUN mkdir -p files/input1 \
            files/input2 \
            files/input3 \
            logs

CMD ["python", "alarm_reset_worker.py"]